version: "3"
services:
  server:
    build:
      context: ./keycloak-backend
      dockerfile: Dockerfile
    image: todos-api-server
    restart: always
    container_name: todos-node-server
    volumes:
      - ./keycloak-backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - keycloak
    links:
      - keycloak
    env_file: ./keycloak-backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - todos-mern-app
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - todos-mern-app
  client:
    build:
      context: ./keycloak-mern
      dockerfile: Dockerfile
    image: todos-react-app
    restart: always
    stdin_open: true
    container_name: todos-react-client
    command: yarn start
    volumes:
      - ./keycloak-mern/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports: 
      - "3000:3000"
    networks:
      - todos-mern-app
  keycloak:
    image: jboss/keycloak
    command: 
      -Djboss.socket.binding.port-offset=101
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8181:8181
    hostname: 'keycloak-host'
    networks:
      - todos-mern-app
networks:
  todos-mern-app:
    driver: bridge
volumes:
  mongo-data:
  node_modules:
  web-root:
    driver: local
