version: "3"
services:
  client:
    image: todos-react-app
    stdin_open: true
    container_name: todos-react-client
    command: yarn start
    volumes:
      - ./keycloak-mern/:/usr/src/app
      - /usr/src/app/app/node_modules
    depends_on:
      - server
    ports: 
      - "3000:3000"
    networks:
      - todos-mern-app
  server:
    image: todos-api-server
    container_name: todos-node-server
    ports:
      - "4000:4000"
    networks:
      - todos-mern-app
    depends_on:
      - mongo
    env_file: ./keycloak-backend/.env
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - todos-mern-app
    volumes:
      - mongo-data:/data/db
  keycloak-container:
    image: jboss/keycloak:5.0.0
    command: 
      -Djboss.socket.binding.port-offset=101
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8181:8181
    networks:
      - todos-mern-app
networks:
  todos-mern-app:
    driver: bridge
volumes:
  mongo-data:
  web-root:
    driver: local
